music/urls.py
from django.urls import path
from . import views

app_name = 'music'
# subprocess of the application!
urlpatterns = [
    # /music/
    path(r'', views.IndexView.as_view(), name='index'),

    # /music/register
    path(r'register/', views.UserFormView.as_view(), name='register'),

    # /music/1/
    path('<int:pk>/', views.DetailsView.as_view(), name='detail'),

    # music/album/add/
    path('album/add/', views.AlbumCreate.as_view(), name='album-add'),

    # music/album/2/
    path('album/<int:pk>/', views.AlbumUpdate.as_view(), name='album-update'),

    # music/album/2/delete/
    path('album/<int:pk>/delete/', views.AlbumDelete.as_view(), name='album-delete'),

    # music/logout/
    path('logout/', views.logout_view, name='logout'),

    # music/song/add/
    path('<int:pk>/song/add/', views.SongAdd.as_view(), name='add-song'),

    # music/songs/
    path('songs/', views.Songs.as_view(), name='songs'),

    # song/favorite/pk
    path('song/favorite/<int:pk>/', views.song_favorite, name='song_favorite'),

    # music/
    path('favorite/<int:pk>/', views.favorite, name='favorite'),

    # music/song/delete/pk
    path('song/delete/<int:pk>/', views.song_delete, name='song_delete')
]

untitled3/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

# the request given from the web user.
# according to the list and requests, it navigates through paths given and certain apps.
# for example - if the user types music it will lead to -music.urls- file and then perform according to request.
urlpatterns = [
    path('admin/', admin.site.urls),
    path('music/', include('music.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

music/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
"""
when you create new class(new table in the database) - it converts it into SQL code file.
you should migrate the app you created to the database, for it to synchronize with everything.
cmd command - (project path) "python manage.py makemigrations music(app)"
and then run the sql file created - "python manage.py migrate"
"""


"""
after you create a table at the database, you can add data 
into it by using the power shell to connect between "manage.py" to the db.

import the models you created(the classes)
the syntax =>"python manage.py shell"
create an object to that classes with the data, hit "<object>.save()"
and then it should be added to the data base.

"""


# when ever you make changes in this file you have to load you migrations inorder for the database to sync!!
# note - only if you delete orr add attributes(data to the table)
# each song in the database is linked to a song. Album - table, Song - table
class Album(models.Model):
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=500)
    genre = models.CharField(max_length=100)
    album_logo = models.FileField()
    is_favorite = models.BooleanField(default=False)

    def get_absolute_url(self):
        return reverse('music:detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.artist + ' - ' + self.album_title


# on delete - means that if(for some reason) the album table gets deleted,
# the songs linked to that table will be deleted as well
class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    song_title = models.CharField(max_length=250)
    is_favorite = models.BooleanField(default=False)
    audio_file = models.FileField(default=None)

    # redirect to the last page. using album's pk.
    def get_absolute_url(self):
        return reverse('music:detail', kwargs={'pk': self.album.pk})

    def __str__(self):
        return "Album {}, Song {}".format(self.album, self.song_title)

music/forms.py
from django.contrib.auth.models import User
from django import forms


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

music/views.py
from django.views import generic
from .models import Album, Song
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.views.generic import View
from django.http import HttpResponseRedirect
from .forms import UserForm


class IndexView(generic.ListView):
    template_name = 'music/index.html'
    context_object_name = 'all_albums'

    def get_queryset(self):
        return Album.objects.all()

# were not getting a list of objects so all we need to say is what object we try to get the detail of - Album
# and the next thing is the template name - plug it into the temlate we defining.


class DetailsView(generic.DetailView):
    model = Album
    template_name = 'music/details.html'

# not a good way to do this. making generic views


class AlbumCreate(CreateView):
    model = Album
    fields = ['artist', 'album_title', 'genre', 'album_logo']


class AlbumUpdate(UpdateView):
    model = Album
    fields = ['artist', 'album_title', 'genre', 'album_logo']


class AlbumDelete(DeleteView):
    model = Album
    success_url = reverse_lazy('music:index')


class UserFormView(View):
    form_class = UserForm
    template_name = 'music/registration_form.html'

    # display a blank form
    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    # process form data
    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():
            user = form.save(commit=False)

            # cleaned (normalized) data
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()

            # returns User objects if credentials are correct
            user = authenticate(username=username, password=password)

            if user is not None:
                if user.is_active:
                    login(request, user)

        return render(request, self.template_name, {'form': form})


def logout_view(request):
    logout(request)
    return redirect('music:index')


class SongAdd(CreateView):
    model = Song
    fields = ['album', 'file_type', 'song_title', 'audio_file']

    def get_absolute_url(self, request):
        return redirect('music/details.html')


class Songs(generic.ListView):
    song_model = Song
    template_name = 'music/songs.html'
    context_object_name = 'all_songs'

    def get_queryset(self):
        return self.song_model.objects.all()


def favorite(request, pk):
    template_name = 'music:index'

    for album in Album.objects.all():
        if album.id == pk:
            if not album.is_favorite:
                album.is_favorite = True
                album.save()
                return HttpResponseRedirect(reverse_lazy(template_name))

            else:
                album.is_favorite = False
                album.save()
                return HttpResponseRedirect(reverse_lazy(template_name))


def song_favorite(request, pk):
    template_name = 'music:songs'

    for song in Song.objects.all():
        if song.id == pk:
            if not song.is_favorite:
                song.is_favorite = True
                song.save()
                return HttpResponseRedirect(reverse_lazy(template_name))

            else:
                song.is_favorite = False
                song.save()
                return HttpResponseRedirect(reverse_lazy(template_name))


def song_delete(request, pk):
    template_name = 'music:index'

    song_list = Song.objects.all()
    for song in song_list:
        if song.id == pk:
            song.delete()
            return HttpResponseRedirect(reverse_lazy(template_name))
"""

from music.models import Album, Song
from django.shortcuts import render, get_object_or_404


def index(request):
    all_albums = Album.objects.all()
    context = {'all_albums': all_albums}
    return render(request, 'music/index.html', context)
    # the http response is builtin in that render response. converts it into http response
    # rendering the template function to our web server


def detail(request, album_id):
    # album = Album.objects.get(pk=album_id)
    album = get_object_or_404(Album, pk=album_id)
    return render(request, 'music/details.html', {'all_albums': album})

"""

templates/music/album_form.html
{% extends 'music/base.html' %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static "music/explanation_albums.css" %}">
{% block title %}Add a new Album{% endblock %}
{% block albums_active %}active{% endblock %}
<!--using bootstrap!!!-->
{% block body %}

<div class="container-fluid" style="float: right">
    <div class="col-sm-12 col-md-7" style="width: 600px;">
        <div class="panel panel-default" style="height: 500px;background: lightgrey">
            <br>
            <h1 style="font-family: 'Segoe UI Historic', sans-serif;margin: 5px;">
                What is Tighter?
            </h1>
            <h4 style="font-family: 'Segoe UI Historic', sans-serif;margin: 5px;">
                Tighter is an app that allows you to upload
                and store all of your music on the cloud
            </h4>
            <br>
            <h2 style="font-family: 'Segoe UI Historic', sans-serif;margin: 5px;">
                How do i add music?
            </h2>

            <h4 style="font-family: 'Segoe UI Historic', sans-serif;margin: 5px;">
                First, create a new album by filling out the form on this page. Once an album is created
                album is created you will be able to add/upload songs.
            </h4>
            <br>
            <h2 style="font-family: 'Segoe UI Historic', sans-serif;margin: 5px;">
                What are some Album logo best practices?
            </h2>
            <br>
            <ul style="font-family: 'Segoe UI Historic', sans-serif;margin: 5px;">
                <li>Have a resolusion of 512x512</li>
                <li>Use common image formats such as JPEG, PNG or GIF</li>
                <li>Remain under the 2MB limit</li>
                <li>Square images look best</li>
            </ul>
        </div>
    </div>
</div>

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'music/form-template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/music/base.html
<!-- the basic stracture for every page were on-->

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Tighter{% endblock %}</title>
    {% load static %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link href="https://fonts.google.com/specimen/DM+Mono?sidebar.open&selection.family=DM+Mono:ital,wght@1,500"
          rel="stylesheet" type="text/css">
    <!-- we always need to put our line of code(the importation-the one below) after
     the bootstrap importation line for it to not over ride ours-->
    <link rel="stylesheet" type="text/css" href="{% static "music/style.css" %}">

    <!-- needed to download the library inorder for it to work-->

    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>

<!-- creating navigation bar - <nav means to create a new part with data, like navigation bar an so on... -->
<body>
    <nav class="navbar navbar-inverse" style="border-radius: 1px"> <!-- inverse -changes the color of navbar to black-->
     <div class="container-fluid">

       <!-- Header -->
         <div class="navbar-header">
             <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
             </button>
             <a class="navbar-brand" href="{% url 'music:index' %}">Tighter</a>
         </div>

         <!-- Items -->
         <div class="collapse navbar-collapse" id="topNavBar">
             <ul class="nav navbar-nav">
                <li class="">
                    <a href="{% url 'music:index' %}">
                        <span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp; Albums
                    </a>
                </li>

                 <li class="">
                    <a href="{% url 'music:songs' %}">
                        <span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp; Songs
                    </a>
                </li>
             </ul>

             <form class="navbar-form navbar-left" role="search" method="get" action="{% url 'music:index' %}">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="{{ request.GET.q }}">
                </div>
                <button type="submit" class="btn btn-default">
                    Search
                </button>
            </form>
             <!-- ul means to open a list of items-->
             <ul class="nav navbar-nav navbar-right">
                 <!-- li means to create an item-->
                 <!-- <a> means to put data inside that item-->
                <li>
                    <a href="{%  url 'music:album-add' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Album
                    </a>
                </li>

                <li>
                    <a href="{% url 'music:logout' %}">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                    </a>
                </li>

             </ul>
         </div>
     </div>
</nav>
<!-- inorder fro us to inclue data from the webpage itself and not only from the nav bar we need to create a block.
we need to include a block of code-->
{% block body  %}
{% endblock %}
</body>
</html>

templates/music/details.html
{% extends 'music/base.html' %}

{% load static %}

{% block title %}Album Details{% endblock %}

{% block body %}
    <link rel="stylesheet" type="text/css" href="{% static "music/song_details.css" %}">

    <br><div class="album_details">
        <img src="{{ album.album_logo.url }}" alt="Albums logo" height="320" width="275" class="image">
        <h1 class="album_name">
            {{ album.album_title }}
        </h1>
        <h5 class="album_genre">
            {{ album.genre }}
        </h5>

        <h3 class="album_artist">
            {{ album.artist }}
        </h3>

        {% if error_message %}
            <p><strong>{{ error_message }}</strong></p>
        {% endif %}
    </div>

    <form action="{% url "music:detail" album.id  %}">
        <input type="submit" class="view_all" value="View All"/>
    </form>

    <form action="{% url "music:add-song" album.id  %}">
        <input type="submit" class="add_song" value="Add New Song"/>
    </form>

    <br>

    <table class="table">
        <caption class="songs_title">All Songs</caption>
        <tr>
            <th>Title</th>
            <th>Audio File</th>
            <th>Favorite</th>
            <th>Actions</th>
        </tr>

        {% for song in album.song_set.all %}
        <tr>
            <td class="table_song_title">
                {{ song.song_title }}
            </td>

            <td>
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10" style="margin: 1px;">
                        <audio controls>
                            <source src="{{ song.audio_file.url }}" type="audio/mp3">
                        </audio>
                    </div>
                </div>
            </td>

            <td>
                <form action="{% url 'music:song_favorite' song.id %}" method="post">
                    {% csrf_token %}

                    {% if song.is_favorite %}
                        <button style="margin:5px;border: none;background: ghostwhite" type="submit">
                            <span class="glyphicon glyphicon-star" style="margin-top:5px;margin-left: 5px;color: gold;font-size: 20px" aria-hidden="true"></span>
                        </button>
                    {% else %}

                        <button style="margin:5px;border: none;background: ghostwhite" type="submit">
                            <span class="glyphicon glyphicon-star-empty" aria-hidden="true" style="margin-top:5px;margin-left: 5px;font-size: 20px"></span>
                        </button>
                    {% endif %}

                </form>
            </td>

            <td>
                <form action="{% url 'music:song_delete' song.id %}" method="post">
                    {% csrf_token %}

                    <button type="submit" class="btn btn-danger">Delete</button>
                </form>
            </td>

        </tr>
        {% endfor %}

    </table>

{% endblock %}


templates/music/form-template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

templates/music/index.html

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"></script>
<!--the data below is what were gonna want to appear in the block section in bae html file-->
{% extends 'music/base.html' %}

{% load static %}

{% block title %}Tighter{% endblock %}
<!-- all were doing is telling him to replace this data (below) with the block we declared in the base file-->
{% block body %}

    <link rel="stylesheet" type="text/css" href="{% static "music/default_music_style.css" %}">

    <ul>
        {%  for album in all_albums %}
            <div class="box" style="margin-right: 20px;margin-bottom: 15px">
                <img src="{{ album.album_logo.url }}" width="235" height="210" alt="Album Logo" class="center">
                <h2 class="title">{{ album.album_title }}</h2>
                <h3 class="artist">{{ album.artist }}</h3>

                <form action="{% url "music:detail" album.id %}">
                    <input type="submit" class="view_details" value="View Details"/>
                </form>

                <!--inorder for me to create a post form i need to make sure putting - csrf_token adn submit on botton.-->
                <form action="{% url "music:album-delete" album.id %}" method="post">
                    {% csrf_token %}
                    <button class="trash" style="margin:5px;color: red" type="submit">
                        <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                    </button>
                </form>


                <form action="{% url 'music:favorite' album.id %}" method="post">
                    {% csrf_token %}

                    {% if album.is_favorite %}
                        <button class="thumbs-up" style="margin:5px" type="submit">
                            <span class="glyphicon glyphicon-thumbs-up" style="color: dodgerblue" aria-hidden="true"></span>
                        </button>
                    {% else %}

                        <button class="thumbs-down" style="margin:5px" type="submit">
                            <span class="glyphicon glyphicon-thumbs-down" aria-hidden="true"></span>
                        </button>
                    {% endif %}

                </form>
                <!--our relations to the songs values-->

                <!--<a href="{% url "music:detail" album.id  %}">{{ album.album_title }}</a>-->
            </div>
        {% endfor %}
    </ul>

{% endblock %}

templates/music/registration_form.html
{% extends 'music/base.html' %}
{% block title %}Reegister{% endblock %}
<!--using bootstrap!!!-->
{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'music/form-template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/music/song_form.html
{% extends 'music/base.html' %}
{% block title %}Add a new Song{% endblock %}
{% block albums_active %}active{% endblock %}
<!--using bootstrap!!!-->
{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'music/form-template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/music/songs.html
<!--make this template!!!-->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"></script>
<!--the data below is what were gonna want to appear in the block section in bae html file-->

{% extends 'music/base.html' %}
{% load static %}
{% block title %}Songs{% endblock %}

{% block body %}

    <link rel="stylesheet" type="text/css" href="{% static "music/song_plugin.css" %}">
    <div class="container-fluid" style="float: right;">
        <div class="col-sm-12 col-md-7" style="width: 600px;">
            <div class="panel panel-default" style="height: 280px;background: lightgrey">
                <br>
                <h2 style="font-family: 'Segoe UI Historic', sans-serif;margin: 5px;">
                    How do i add songs?
                </h2>

                <h4 style="font-family: 'Segoe UI Historic', sans-serif;margin: 5px;">
                    After creating an album, head to Add new song button and add songs related to albums
                </h4>
                <br>
                <h2 style="font-family: 'Segoe UI Historic', sans-serif;margin: 5px;">
                    What are some Song Audio file best practices?
                </h2>
                <br>
                <ul style="font-family: 'Segoe UI Historic', sans-serif;margin: 5px;">
                    <li>Use common audio file formats such as mp3</li>
                </ul>
            </div>
        </div>
    </div>
    <ul>
        {%  for song in all_songs %}
            <div class="box" {% if song.is_favorite %}

                style="background: lightyellow"
                {% else %}
                style="background: ghostwhite"
                {% endif %}>

                <img src="{{ song.album.album_logo.url }}" width="250px" height="250px" style="border-radius: 8px" alt="Album Logo">
                <h2 class="title">{{ song.song_title }}</h2>
                <!--inorder for me to create a post form i need to make sure putting - csrf_token adn submit on botton.-->
                <var class="navbar original" style="margin-left: 40px">
                    <audio controls class="play_bar">
                        <source src="{{ song.audio_file.url }}" type="audio/mp3">
                    </audio>
                </var>

            </div>
        {% endfor %}
    </ul>

{% endblock %}